# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.2.4"

Vagrant.configure(2) do |config|

	config.vm.box = "ubuntu/bionic64"
    config.vm.box_version = "20190314.0.0"

	config.vm.box_check_update = false

	config.vm.hostname = "canigodev"

	config.vm.provider "virtualbox" do |vb|
        vb.default_nic_type = "virtio"
		vb.gui = true
		vb.memory = "6124" # 6G
		vb.cpus = 2
		# vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
		# See https://github.com/chef/bento/issues/682
		vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
		vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
		vb.customize ["modifyvm", :id, "--vram", "128"]
		vb.name = "CanigoDev-3.0.0-b1"
	end

	config.vm.provision "file", source: "resources", destination: "/tmp/resources"
	config.vm.provision "shell", path: "resources/provision.sh"

end
